/**
 * The message model and the LLM capability contract (MASTER_PLAN.md §2.1, §2.9).
 *
 * A `Message` is the single currency of the agent loop. A `LlmProvider` is what a
 * concrete backend (OpenAI-compatible, Anthropic) implements; the router composes
 * them. Consumers of `magoco.llm.complete` see only `LlmRequest`/`LlmResponse` and
 * never know which backend served them (MASTER_PLAN.md §1.5, capability seam).
 */

/** A participant in a conversation. */
export type Role = 'system' | 'user' | 'assistant' | 'tool';

/** One message in a conversation. */
export interface Message {
  readonly role: Role;
  readonly content: string;
  /** Present only on assistant messages that requested tool calls. */
  readonly toolCalls?: readonly ToolCall[];
  /** Present only on tool-result messages. */
  readonly toolCallId?: string;
  /**
   * Present only on tool-result messages whose original id was regenerated by the
   * adapter (e.g. Anthropic issues its own ids) — kept so the loop can correlate.
   */
  readonly toolCallIdAlias?: string;
}

/** A request the model made to call a capability. */
export interface ToolCall {
  /** The model's own id for this call. */
  readonly id: string;
  /** The capability id — a tool *is* a capability (see tools.ts). */
  readonly capability: string;
  /** JSON string exactly as the model produced it. Validated once, at the seam. */
  readonly arguments: string;
}

/** How the loop describes a capability it will let the model call. */
export interface ToolSchema {
  readonly capability: string;
  readonly description: string;
  /** A JSON Schema describing the arguments. */
  readonly parameters: object;
}

/** A weight class the agent asks for, never a model name. */
export type Tier = 'fast' | 'balanced' | 'strong';

/** A request to the LLM capability. */
export interface LlmRequest {
  /** Weight class for model selection. Default `balanced`. */
  readonly tier?: Tier;
  readonly messages: readonly Message[];
  /** Capabilities the model may call this turn. */
  readonly tools?: readonly ToolSchema[];
  /** When set, the reply must validate against this schema or the call is malformed. */
  readonly outputSchema?: object;
  /** Stream the reply instead of returning it whole. Default false. */
  readonly stream?: boolean;
  /** Pin a model, overriding the tier mapping. */
  readonly model?: string;
  readonly temperature?: number;
  readonly maxTokens?: number;
  /** Whose run this is — propagated for cost attribution. */
  readonly agentId: string;
  readonly sessionId: string;
}

/** One piece of a streamed reply. */
export interface LlmChunk {
  readonly delta?: string;
  readonly toolCalls?: readonly ToolCall[];
  readonly done?: boolean;
}

/** Token and cost accounting for one call. */
export interface Usage {
  readonly promptTokens: number;
  readonly completionTokens: number;
  /** USD. 0 when the provider reports no pricing for the model. */
  readonly costUsd: number;
  /** False when the numbers are estimated locally rather than provider-reported. */
  readonly countedByProvider: boolean;
}

/** A non-streamed reply. */
export interface LlmDone {
  readonly stream: false;
  readonly message: Message;
  readonly usage: Usage;
  readonly provider: string;
  readonly model: string;
  readonly latencyMs: number;
}

/** A streamed reply. The chunks arrive now; usage resolves when the stream closes. */
export interface LlmStream {
  readonly stream: true;
  readonly chunks: AsyncIterable<LlmChunk>;
  readonly usage: Promise<Usage>;
  readonly provider: string;
  readonly model: string;
}

export type LlmResponse = LlmDone | LlmStream;

/**
 * What a concrete backend implements.
 *
 * The router owns fallback; a provider fails and the next candidate is tried. A
 * provider therefore reports failure by *throwing*, and reports success by returning.
 */
export interface LlmProvider {
  /** Name as it appears in config (`openai`, `anthropic`, …). */
  readonly name: string;
  /** True when this provider can serve `model`. */
  serves(model: string): boolean;
  /** Perform one round trip. Never retries — that is the router's job. */
  complete(req: LlmRequest): Promise<LlmResponse>;
}

/**
 * Thrown when every candidate provider for a router failed. The `causes` are the
 * underlying errors, in try order, so a caller can see the whole picture.
 */
export class NoProviderSucceededError extends Error {
  constructor(readonly router: string, readonly causes: Array<{ provider: string; error: unknown }>) {
    super(
      `router ${router}: every provider failed — ` +
        causes.map((c) => `${c.provider}: ${String(c.error)}`).join('; '),
    );
    this.name = 'NoProviderSucceededError';
  }
}

/** Thrown when a provider returned something that is not a valid reply. */
export class MalformedReplyError extends Error {
  constructor(provider: string, reason: string) {
    super(`provider ${provider} returned a malformed reply: ${reason}`);
    this.name = 'MalformedReplyError';
  }
}
